baseURL = 'https://sanfranciscoysantaclara.es/'
languageCode = 'es-es'
title = 'Parroquia San Francisco y Santa Clara de Asís'

# Para URLs más limpias
relativeURLs = false

# No publicar automáticamente contenido con fecha futura
buildFuture = false

# Taxonomías (CLAVE para categorías y etiquetas)
[taxonomies]
  category = "categorias"
  tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.destacada]
  mediaType = "application/json"
  baseName = "destacada"
  isPlainText = true



