baseURL = 'https://sanfranciscoysantaclara.es/'
languageCode = 'es-es'
title = 'Parroquia San Francisco y Santa Clara de Asís'

# Para URLs más limpias
relativeURLs = false

# Taxonomías (CLAVE para categorías y etiquetas)
[taxonomies]
  category = "categorias"
  tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]



