name: Deploy Hugo to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.159.2'
          extended: true

      - name: Generar sitio Hugo
        run: hugo

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy a Firebase
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"